version: '2'
services:

  postgresql:
    image: postgres:9.6

  web:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - postgresql
    environment:
      - DEBUG=${DEBUG}
      - SQLALCHEMY_DATABASE_URI=postgres://postgres@postgresql/postgres
      - GITHUB_AUTH_TOKEN=${GITHUB_AUTH_TOKEN}
    ports:
      - "5000:5000"
    volumes:
      - $PWD:/app
